name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag packed-log-viewer:$(git rev-parse --short HEAD)
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get tag
      uses: actions/checkout@v3
      run: short_sha=$(git rev-parse --short $GITHUB_SHA)
    - name: Tag
      run: |
          docker tag packed-log-viewer:latest ${{ secrets.DOCKERHUB_USERNAME }}/packed-log-viewer:latest
          docker tag packed-log-viewer:${{ env.short_sha }} ${{ secrets.DOCKERHUB_USERNAME }}/packed-log-viewer:${{ env.short_sha }}
    - name: Push
      run: |
        docker push -a ${{ secrets.DOCKERHUB_USERNAME }}/packed-log-viewer
